### ISSUE TITLE
@local_jdk is not found when running in Ubuntu on Windows 10

### ISSUE THREAD

**Issue by ningxie1991** [CodeIntelligenceTesting/jazzer#103]
Hello, I am trying to run the example, however, after setting local jdk to JAVA_HOME I am still getting the warning and bazel could not find my local jdk. I couldn't find any solutions online. Please help.

`nxie@LAPTOP-8Q6L74UG:/mnt/c/users/ningx/dev/github/jazzer$ bazel run //:jazzer
WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
Starting local Bazel server and connecting to it...
ERROR: /home/nxie/.cache/bazel/_bazel_nxie/7d80d092e073fb44fce0d67ba176764e/external/local_jdk/BUILD.bazel:3:10: in fail_rule rule @local_jdk//:jdk:
Traceback (most recent call last):
        File "/home/nxie/.cache/bazel/_bazel_nxie/7d80d092e073fb44fce0d67ba176764e/external/bazel_tools/tools/jdk/fail_rule.bzl", line 19, column 13, in _fail_rule_impl
                fail("%s %s" % (ctx.attr.header, ctx.attr.message))
Error in fail: Auto-Configuration Error: Cannot find Java binary bin/java in /home/nxie/.cache/bazel/_bazel_nxie/install/1a4a2fac02d50c77031d44c0d91b8920/embedded_tools/tools/jdk/nosystemjdk; either correct your JAVA_HOME, PATH or specify embedded Java (e.g. --javabase=@bazel_tools//tools/jdk:remote_jdk11)
INFO: Repository remotejdk11_linux instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:52:6: in <toplevel>
  /home/nxie/.cache/bazel/_bazel_nxie/7d80d092e073fb44fce0d67ba176764e/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:18: in maybe
Repository rule http_archive defined at:
  /home/nxie/.cache/bazel/_bazel_nxie/7d80d092e073fb44fce0d67ba176764e/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Repository com_google_absl instantiated at:
  /mnt/c/users/ningx/dev/github/jazzer/WORKSPACE.bazel:6:20: in <toplevel>
  /mnt/c/users/ningx/dev/github/jazzer/repositories.bzl:81:10: in jazzer_dependencies
  /home/nxie/.cache/bazel/_bazel_nxie/7d80d092e073fb44fce0d67ba176764e/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:18: in maybe
Repository rule http_archive defined at:
  /home/nxie/.cache/bazel/_bazel_nxie/7d80d092e073fb44fce0d67ba176764e/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Repository 'com_google_absl' used the following cache hits instead of downloading the corresponding file.
 * Hash '6ead5ca816dee2052e80ef746ab88e319f7cf40392e9dcc67d56d2d1e0043660' for https://github.com/abseil/abseil-cpp/archive/3a2d6572d06709da32a17f053ca1e3c8e2af90df.zip
If the definition of 'com_google_absl' was updated, verify that the hashes were also updated.
ERROR: Analysis of target '//:jazzer' failed; build aborted: Analysis of target '@local_jdk//:jdk' failed
INFO: Elapsed time: 3.526s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (31 packages loaded, 255 targets configured)
FAILED: Build did NOT complete successfully (31 packages loaded, 255 targets configured)
    Fetching @jazzer_com_github_gflags_gflags; fetching
    Fetching @com_google_glog; fetching
    Fetching ...e_absl; Extracting /home/nxie/.cache/bazel/_bazel_nxie/7d80d092e073fb44fce0d67ba176764e/external/com_g\
oogle_absl/temp1555407049090310124/3a2d6572d06709da32a17f053ca1e3c8e2af90df.zip
    Fetching ...e_glog; Extracting /home/nxie/.cache/bazel/_bazel_nxie/7d80d092e073fb44fce0d67ba176764e/external/com_g\
oogle_glog/temp4216640165572278970/8d40d7564d4a06d77d707d7c4a50c8b5dc45dd80.tar.gz
    Fetching ...gflags; Extracting /home/nxie/.cache/bazel/_bazel_nxie/7d80d092e073fb44fce0d67ba176764e/external/jazze\
r_com_github_gflags_gflags/temp17373977854442152533/827c769e5fc98e0f2a34c47cef953cc6328abced.tar.gz
nxie@LAPTOP-8Q6L74UG:/mnt/c/users/ningx/dev/github/jazzer$ echo $JAVA_HOME
/mnt/c/Users/ningx/Java/jdk-15.0.2
nxie@LAPTOP-8Q6L74UG:/mnt/c/users/ningx/dev/github/jazzer$`

**Comment by fmeum** [comment]
Everything runs and tests fine for me on Windows with Ubuntu 20.04 and the `openjdk-16-jdk` package installed. Is it possible that you have a JRE installed, but no JDK?

**Comment by ningxie1991** [comment]
> Everything runs and tests fine for me on Windows with Ubuntu 20.04 and the `openjdk-16-jdk` package installed. Is it possible that you have a JRE installed, but no JDK?

Hi Fabian,
Thanks for the reply. I tried installing openjdk-15-jdk and clone the jazzer source again to my home path, then it's working now. However, there's another error now:
"clang-12: error: unknown argument: '-fno-canonical-system-headers' " 

nxie@LAPTOP-8Q6L74UG:/usr/local/bin$ gcc -version
gcc: error: unrecognized command line option ‘-version’
gcc: fatal error: no input files

**Comment by fmeum** [comment]
Could you check whether you still see this error after a `bazel clean --expunge`?

**Comment by ningxie1991** [comment]
> Could you check whether you still see this error after a `bazel clean --expunge`?

That solved the problem. Thank you!
