### ISSUE TITLE
Jazzer documentation

### ISSUE THREAD

**Issue by Pertence** [CodeIntelligenceTesting/jazzer#117]
I have a question, where can I find the documentation about the arguments that the jazzer program can take?

**Comment by fmeum** [comment]
First of all, Jazzer accepts all arguments that libFuzzer accepts (those starting with a single dash).

The arguments it supports on top of that are mostly explained in the README or used in the examples (https://github.com/CodeIntelligenceTesting/jazzer/blob/main/examples/BUILD.bazel). All arguments can be obtained by running Jazzer with the `--help` argument. 

Let me know if you have questions about a particular argument and I will see whether I can add documentation.

**Comment by Pertence** [comment]
Thanks for the answer.
