### ISSUE TITLE
slow-unit does not reproduce and hangs jazzer

### ISSUE THREAD

**Issue by thapr0digy** [CodeIntelligenceTesting/jazzer#121]
I'm currently testing GZIPInputStream and a portion of the Jackson library. My fuzzer ends up writing a slow-unit to disk, but never writes the reproducer .java. It also never finishes and just sits in futex syscall when I look through /proc/pid/syscall.

I'm basically asking to see is this an issue with jazzer or did I find a not reproducible bug in my fuzz test. I can post my testcase and whatever else is needed. Just didn't want to end up disclosing a 0-day in the library here if it exists.

What kind of information would be beneficial to your team to see if it's jazzer?

**Comment by fmeum** [comment]
We currently don't generate Java reproducers for timeouts and slow units, only for actual crashes. But the usual slow unit crash files written by libFuzzer should still be there and can be used to reproduce the issue with Jazzer (just pass the path to the file as a positional argument).

Would a way to generate a Java reproducer from an ordinary crash/timeout/slow-input input file help you? This is something I've been thinking of implementing for some time.

As to why the fuzzer never finishes I can't say easily. Could you maybe post the (possibly redacted) logs?

**Comment by thapr0digy** [comment]
So I've attempted to diagnose this with no luck still so here's what I have. 

When I use the slow-unit input file, the input does not hang for the specified time as shown when it's generating the slow-unit file. It looks to just be waiting on the futex syscall due to contention of some input/directory. I think generating a Java reproducer for a slow-input would be beneficial here. 

Here's a portion of the logs that may be helpful in looking farther into this:

`
INFO: Instrumented *.io.IOContext (took 3 ms, size +56%)
INFO: Instrumented *.util.BufferRecyclers (took 1 ms, size +52%)
INFO: Instrumented *.util.BufferRecycler (took 1 ms, size +46%)
INFO: Instrumented * (took 4 ms, size +65%)
INFO: Instrumented * (took 33 ms, size +116%)
INFO: Instrumented * (took 1 ms, size +74%)
INFO: Instrumented * (took 2 ms, size +59%)
Executed slow-unit-1a12d0edce2c8575fdf42f82b1645484acce6cee in 53 ms
***
*** NOTE: fuzzing was not performed, you have only
***       executed the target code on a fixed set of inputs.
***`

This was while attempting to run the slow-unit file. Here is the output while running the fuzzer and it generating the slow-unit file. If you need the code to reproduce, I can give this I guess. Since it's not reproducing, there must be something I'm missing here other than it's locking up on sched_yield and futex syscalls when running strace.

`#71	INITED cov: 223 ft: 238 corp: 19/293b exec/s: 0 rss: 541Mb
INFO: Instrumented com.fasterxml.jackson.databind.type.ClassStack (took 2 ms, size +35%)
#65536	pulse  cov: 223 ft: 238 corp: 19/293b lim: 668 exec/s: 32768 rss: 1141Mb
INFO: Instrumented com.fasterxml.jackson.core.json.DupDetector (took 1 ms, size +65%)
#131072	pulse  cov: 223 ft: 238 corp: 19/293b lim: 1318 exec/s: 32768 rss: 1303Mb
#262144	pulse  cov: 223 ft: 238 corp: 19/293b lim: 2620 exec/s: 32768 rss: 1448Mb
#524288	pulse  cov: 223 ft: 238 corp: 19/293b lim: 4096 exec/s: 32768 rss: 1898Mb
#1048576	pulse  cov: 223 ft: 238 corp: 19/293b lim: 4096 exec/s: 31775 rss: 2714Mb
#2097152	pulse  cov: 223 ft: 238 corp: 19/293b lim: 4096 exec/s: 33288 rss: 3468Mb
#4194304	pulse  cov: 223 ft: 238 corp: 19/293b lim: 4096 exec/s: 33825 rss: 4131Mb
Slowest unit: 667 s:
artifact_prefix='./'; Test unit written to ./slow-unit-386a2fc8523d993773d34316b2ddca2a5bb79e02
Base64: H4sIQZdgLEBs0wD0AQv+AAD/fg==
#8388608	pulse  cov: 223 ft: 238 corp: 19/293b lim: 4096 exec/s: 8858 rss: 5803Mb
#16777216	pulse  cov: 223 ft: 238 corp: 19/293b lim: 4096 exec/s: 13651 rss: 6120Mb`

**Comment by thapr0digy** [comment]
Additional information from this same harness that results in an OutOfMemory error:
```
#25739173       REDUCE cov: 223 ft: 939 corp: 242/6303b lim: 10000 exec/s: 17924 rss: 6409Mb L: 173/522 MS: 4 ChangeByte-ShuffleBytes-EraseBytes-InsertByte-                                                                                                                      
Slowest unit: 10 s:                                                                                                                                                                                                                                                               
artifact_prefix='./'; Test unit written to ./slow-unit-d808e49174a2f6e47ca4cc00656e16b229204670                                                                                                                                                                                   
Base64: H4sIYMi0AfSLCGDItAH0AUEBCGDItAH0iwhgyLQB9AH+AAAeiw==                                                                                                                                                                                                                      
*** java.lang.instrument ASSERTION FAILED ***: "!errorOutstanding" with message can't create name string at ./src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 827                                                                                               
                                                                                                                                                                                                                                                                                  
== Java Exception: java.lang.OutOfMemoryError: Java heap space                                                                                                                                                                                                                    
DEDUP_TOKEN: bac12c1dd0658676                                                                                                                                                                                                                                                     
== libFuzzer crashing input ==                                                                                                                                                                                                                                                    
MS: 2 ShuffleBytes-ChangeBit-; base unit: 63fa63eff6757bdab3b066013764fde36ef56cc6                                                                                                                                                                                                
0x1f,0x8b,0x8,0x20,0x8b,0x8,0xb,0xfe,0x3e,0x0,0x61,0xf4,0x1,0xb,0xfe,0x0,0x1,0x1,0x10,                                                                                                                                                                                            
\x1f\x8b\x08 \x8b\x08\x0b\xfe>\x00a\xf4\x01\x0b\xfe\x00\x01\x01\x10                                                                                                                                                                                                               
artifact_prefix='./'; Test unit written to ./crash-f64cad2a16eb526cb037b3fe8100be8595099769                                                                                                                                                                                       
Base64: H4sIIIsIC/4+AGH0AQv+AAEBEA==                                                                                                                                                                                                                                              
reproducer_path='.'; Java reproducer written to ./Crash_f64cad2a16eb526cb037b3fe8100be8595099769.java 
```

**Comment by fmeum** [comment]
@mdindoffer Do you have an example fuzz target with which I could reproduce the issue?

**Comment by mdindoffer** [comment]
@fmeum Of couse: https://github.com/mdindoffer/jazzer-false-timeout

It fuzzes the https://github.com/capnproto/capnproto-java - I've precompiled the protocol schema and included it in the sources. So everything is ready to go, just build it with:
`mvn clean package -DskipTests`
and fuzz.
For a corpus there's one file in the `src/main/resources`. 

I'm sorry I don't have the seeds anymore, but you should be able to encounter it very quickly.

There's also one junit test as a reproducer with one of the false positive timeout inputs I've observed in the `src/test/resources`.

Not sure if it matters, but I've been fuzzing with `-use_value_profile=1`

**Comment by fmeum** [comment]
Thanks for the complete example. I'll take a deep look next week and will try to find the root cause.

**Comment by thapr0digy** [comment]
@fmeum - I'll post mine as well. It's probably just easier this way: https://github.com/thapr0digy/gzipfuzzer

**Comment by fmeum** [comment]
@mdindoffer The slow units encountered with the fuzz target you provided tend to produce `AddressBook` instances with a large number of `People` - on the order of `Integer.MAX_VALUE`. Surprisingly, even though the inputs are typically less than ~100 bytes long, `capnproto-java` still iterates over all these (empty) `People` objects, which takes on the order of 100 seconds with Jazzer's coverage instrumentation. Without Jazzer's coverage instrumentation, this iteration is probably highly optimizable and thus takes only ~100 ms on my machine, which is still *a lot* of time to spend on such a small input.

All in all, I think these samples arise from actual bugs in `capnproto-java`, although minor ones, whose impact is greatly amplified by the overhead introduced by Jazzer's coverage instrumentation. The parser should not enter loops with an attacker-controlled iteration count that is not bounded by the input length. Even though the parser is still not extremely slow on these samples, it seems quite possible to construct very short capnproto messages that would take on the order of seconds or possibly minutes to parse. That would not be severe, but certainly undesirable. Maybe the parser can be augmented with some additional checks that bound iteration counts by the message length?

@thapr0digy I haven't tried your example yet, but expect the root cause to be similar. Could you go through the slow units with a debugger and check whether it triggers any loops with very large iteration counts?

**Comment by mdindoffer** [comment]
OMG, you are absolutely right. It did not even cross my mind that instrumentation could have such large effect.

So not a Jazzer bug after all. I will look into those big loops this week.

Thanks @fmeum !

**Comment by fmeum** [comment]
@thapr0digy I will close this issue for now, but feel free to post here if the issue you are experiencing is not caused by long loops + instrumentation overhead.
