### ISSUE TITLE
Jazzer aborts / does not write reproducer when using ASAN

### ISSUE THREAD

**Issue by ASKobayashi-db** [CodeIntelligenceTesting/jazzer#187]
This is a fantastic project!

When running this project with ASAN, upon finding an issue, jazzer aborts without writing a reproducer or DEDUP_TOKEN This also means that --keep-going does not work.  It can be reproduced even with the default example:

Example:
```
> bazel run //examples:ExampleFuzzerWithASan

INFO: Analyzed target //examples:ExampleFuzzerWithASan (0 packages loaded, 0 targets configured
INFO: Found 1 target...
Target //examples:ExampleFuzzerWithASan up-to-date:
  bazel-bin/examples/ExampleFuzzerWithASan
INFO: Elapsed time: 0.104s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action

...

Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==158060==ABORTING
MS: 1 CMP- DE: "secret_in_native_library"-; base unit: 16fa22809a4e348998de632dc7f5e03577240500
0x61,0x62,0xe4,0xfd,0x1,0x63,0x1,0x6a,0x61,0x7a,0x7a,0x65,0x72,0x73,0x65,0x63,0x72,0x65,0x74,0x5
f,0x69,0x6e,0x5f,0x6e,0x61,0x74,0x69,0x76,0x65,0x5f,0x6c,0x69,0x62,0x72,0x61,0x72,0x79,0xe4,0xfd
,0xe,0x1,
ab\xe4\xfd\x01c\x01jazzersecret_in_native_library\xe4\xfd\x0e\x01
artifact_prefix='/home/askobayashi/.cache/bazel/_bazel_askobayashi/c359549acfcfeb7d27b63645e432b
e8d/execroot/jazzer/bazel-out/k8-opt/testlogs/examples/ExampleFuzzerWithASan/test.outputs/'; Tes
t unit written to /home/askobayashi/.cache/bazel/_bazel_askobayashi/c359549acfcfeb7d27b63645e432
be8d/execroot/jazzer/bazel-out/k8-opt/testlogs/examples/ExampleFuzzerWithASan/test.outputs/crash
-4cfe80e1c06525a244d3b5ed9dd59c0d70e6951d
Base64: YWLk/QFjAWphenplcnNlY3JldF9pbl9uYXRpdmVfbGlicmFyeeT9DgE=
```

The Base64 is the last line and it returns to console.  As you can see, the Test unit is written, but neither a reproducer or DEDUP_TOKEN  is created.

When using a non-asan target, you will typically see a line like:
`Java reproducer written to ...`

This is on ubuntu 20.04.  I'd love to figure out what's going on here so I can run it with keep_going and DEDUP findings.

Thanks!

**Comment by fmeum** [comment]
Both the `--keep_going` logic and the Java reproducers are additional features for Java exceptions that are built into Jazzer on top of libFuzzer. The report you are seeing is generated by AddressSanitizer applied to native code, without Jazzer being involved at all. This behavior is thus expected, but that of course doesn't mean that we couldn't improve on it.

Let's go over the individual features you mentioned:

1. Jazzer computes a `DEDUP_TOKEN` from a JVM stack trace. Its purpose is not only to enable the `--keep_going` mode (not available in libFuzzer itself), but also to reliably minimize crashing inputs. The latter is what `DEDUP_TOKEN`s are used for by libFuzzer. If you want to have them printed also for native findings, you have to pass the `dedup_token_length` option to the sanitizer with a non-zero value indicating the number of stack frames that should go into the token. For example, try running
```
ASAN_OPTIONS=dedup_token_length=3 bazel run //examples:ExampleFuzzerWithASan
```
which should give you a `DEDUP_TOKEN` of `parseInternal(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)--Java_com_example_ExampleFuzzerWithNative_parse--`.

2. A `--keep_going` mode that also works for native findings would have to be implemented in libFuzzer itself. This could make for a useful addition, but the upstream maintainers would of course have to approve of it. But keep in mind that this feature may not work as well for native findings as it does for Java exceptions: While recovering from an uncaught Java exception is usually possible, AddressSanitizer findings usually imply some level of memory corruption that may leave the program under test in an undefined state.

3. Java reproducers for native findings are something I would like to add (as well as for timeouts and slow units). While this would require an additional libFuzzer patch, which we want to avoid if possible, it would likely be a very small one. If you would find this useful, I could track this as a separate feature request.

**Comment by ASKobayashi-db** [comment]
Wow thank you for the quick and thorough reply!  I'll reply in order as well.

1) This is great. The "hardest" part of doing a simple invocation wrapper is generating a DEDUP token.  It wouldn't be hard to hash the stack, but much easier (and presumably a more sophisticated solution) to get the library to do it for you.. 

2) I suspected the issue was with the fact that the abort is triggered.  Good to get confirmation on that fact.  Regarding memory corruption, I would think that in fork mode any such corruption would be cleaned out since memory in the forked process would be COW.  That being said, this isn't that big of a deal.. it's more a "would be nice" feature.  I will say that most fuzzers I've used or created in the past default to "run forever, write trigger file" so it is a little strange that Jazzer quits on the first finding by default.  Typical usage is to spin up long running processes on multiple machines and check results every now and then.

3) I would certainly love to see native reproducers, but this is also totally a "convenience" type feature.  The trigger file is all you really need.  I would certainly use it if it was created, but there may well be other more valuable features you should spend your time on!

I just wanted to once again compliment you / CodeIntelligence.  The quality of this project is impressive and for the most part 'just worked', which is high praise!  I consider this issue closed! Feel free to reopen it if you should want to link it to a feature request (or have me make the request).

Cheers!
