### ISSUE TITLE
libFuzzer Dictionary Support

### ISSUE THREAD

**Issue by schirrmacher** [CodeIntelligenceTesting/jazzer#188]
When applying the `-dict` [flag of libFuzzer](https://llvm.org/docs/LibFuzzer.html#dictionaries) the fuzzing just stops:

```
Executed dictionaries/json.dict in 2097 ms
***
*** NOTE: fuzzing was not performed, you have only
***       executed the target code on a fixed set of inputs.
***
```

Is it because dicts are not supported at the moment?

**Comment by fmeum** [comment]
Dictionaries are fully supported (in the same way as with libFuzzer) and actively used in OSS-Fuzz. Judging by the command output, it seems that Jazzer/libFuzzer treated `dictionaries/json.dict` as an input file, not a dictionary. Could you provide the full command line invocation?

**Comment by schirrmacher** [comment]
The command I used was:

```
docker run -it ciot-hub-fuzz jazzer/jazzer --cp="dependencies.jar" --target_class="$TARGET" -dict dictionaries/json.dict
```

**Comment by schirrmacher** [comment]
I guess I found the issue. It should be `-dict=dictionaries/json.dict` instead of `-dict dictionaries/json.dict`.

**Comment by fmeum** [comment]
You should be able to omit the `=` in non-libFuzzer Jazzer flags, which would make these command lines more consistent.
