### ISSUE TITLE
FuzzedDataProvider.consumeChar(char min, char max) returns values outside of range

### ISSUE THREAD

**Issue by katherine-hough** [CodeIntelligenceTesting/jazzer#249]
Calls to `FuzzedDataProvider.consumeChar(char min, char max) ` can return values outside of the range [min, max]. For example, fuzzing the following method with Jazzer produces an unexpected assertion error:
```
import com.code_intelligence.jazzer.api.FuzzedDataProvider;

public class FuzzTarget {
    public static void fuzzerTestOneInput(FuzzedDataProvider provider) {
    	char min = 'a';
    	char max = 'b';
    	char c = provider.consumeChar(min, max);
    	assert(c >= min && c <= max);
    }
}
```

I believe that the issue is that line 667 of fuzzed_data_provider.cpp uses a function pointer to `ConsumeIntegral ` instead of `ConsumeIntegralInRange`.

**Comment by fmeum** [comment]
Good catch, your analysis of the cause is also correct. Do you want to submit a PR with the fix you suggested?

**Comment by katherine-hough** [comment]
I created a PR. Thank you for the fast response.
