### ISSUE TITLE
the recording FuzzedDataProvider skips methods implemented as interface defaults

### ISSUE THREAD

**Issue by dgardnersf** [CodeIntelligenceTesting/jazzer#265]
The pickX methods that are implemented as FuzzedDataProvider interface defaults have internal calls to the data provider that never get recorded. This causes playback via the CannedFuzzedDataProvider to fail with class cast exceptions since the stream does not contain the needed input.  A workaround is to copy/paste the default methods into a helper class that delegates appropriately to the data provider native methods.

**Comment by fmeum** [comment]
Good catch, I completely missed this subtlety of using proxies. This seems suprisingly difficult to resolve without breaking backwards compatibility or duplicating all default methods. I will see whether I can find a workaround.

**Comment by fmeum** [comment]
@dgardnersf Could you check whether #266 resolves the issue? I added test coverage for the FuzzedDataProvider --> RecordingFuzzedDataProvider --> CannedFuzzedDataProvider workflow to prevent this from breaking in the future.
