### ISSUE TITLE
Constant string generated for crash file is too long

### ISSUE THREAD

**Issue by cdanielgomes** [CodeIntelligenceTesting/jazzer#269]
Hi there.

I am generating 2D matrix with random dimensions like the code below. 

```java
            int vectorLen = data.consumeInt(1, 500);
            int matrixLen = data.consumeInt(1, 500);

            double[][] matrix = new double[matrixLen][vectorLen];

            for (int i = 0; i < matrixLen; ++i) {
                double[] tmp_vector = new double[vectorLen];
                for (int j = 0; j < vectorLen; ++j) {
                    tmp_vector[j] = data.consumeDouble();
                }
                matrix[i] = tmp_vector;
            }
```

Jazzer runs the code, but the file created has a huge string feeding ```CannedFuzzedDataProvider```. 

I do not know if this is a bug or if this issue is intended to be like it is, but Jazzer is generating a file that does not compile.

I let here a controlc.com for the crash file if you want to check it. [Crash file](https://controlc.com/2a6df309)

**Comment by fmeum** [comment]
Java source files have a limit of 64KB on the size of string constants and Jazzer should honor that limit when generating Java reproducers. We might be able to get away with String concatenation, but I will have to investigate solutions.

**Comment by bertschneider** [comment]
@cdanielgomes As @fmeum pointed out the generated data string is tool long. I created PR #283 to fix this issue.
