### ISSUE TITLE
Specify external jar file as a dependency for fuzzer

### ISSUE THREAD

**Issue by prashast** [CodeIntelligenceTesting/jazzer#307]
Hi, instead of importing a library from maven for fuzzing, I wanted to import a locally-downloaded jar file containing the library to be fuzzed on the classpath. Is that possible to do so by tweaking the rules in `jazzer/examples/BUILD.bazel`?

As an example, let's say I had this as the original build rule for the fuzz target.
```
java_fuzz_target_test(
    name = "GifImageParserFuzzer",
    srcs = [
        "src/main/java/com/example/GifImageParserFuzzer.java",
    ],
    target_class = "com.example.GifImageParserFuzzer",
    deps = [
        "@maven//:org_apache_commons_commons_imaging",
    ],
)
```

How can I update the `deps` to not retrieve the imaging library from maven but instead use my own local copy of the library as a jar file instead? 

Alternatively is there someway for me to alter the below command to include my custom library on the classpath? I tried adding `-- --cp=/path/to/custom/jar/file --target_class=com.example.GifImageParserFuzzer` at the end of the below command but it did not work as expected.
```
./bazelisk-linux-amd64 run //examples:GifImageParserFuzzer -- --cp=/path/to/custom/jar/file --target_class=com.example.GifImageParserFuzzer
```

[UPDATE] I was able to finally fuzz my own custom library by using the jazzer binary and including the custom library on the classpath like so (as referred to [here](https://github.com/CodeIntelligenceTesting/jazzer#running-the-fuzzer) ) . However, I would still appreciate it if you could let me know if there is a way to do the same thing using bazel as well. It would make my workflow slightly simpler.
```
./jazzer --cp=fuzz_target.jar:custom_library.jar --target_class=com.example.MyFuzzTarget
```

**Comment by fmeum** [comment]
@prashast What you mention in your update is exactly how you should use Jazzer (although there is also a Docker image in case that is more convenient). The `java_fuzz_target_test` Bazel macro is something we use to verify examples don't break in Jazzer's CI - it is not meant to be used for more than toy examples. If you want to use Jazzer in Bazel, proper integration is available over at [rules_fuzzing](https://github.com/bazelbuild/rules_fuzzing).

**Comment by prashast** [comment]
Thanks for clarifying the intended usage. :)
