### ISSUE TITLE
**********_[![image](https://user-images.githubusercontent.com/100020410/161419315-a712a56a-c6ba-4945-a644-c27e95345e88.jpeg)]()_

### ISSUE THREAD

**Issue by Puma2511a** [CodeIntelligenceTesting/jazzer#377]
**********_[![image](https://user-images.githubusercontent.com/100020410/161419315-a712a56a-c6ba-4945-a644-c27e95345e88.jpeg)]()_

__Originally posted by @Puma2511a in https://github.com/CodeIntelligenceTesting/jazzer/pull/373#issuecomment-1086803561__

**Comment by fmeum** [comment]
@Puma2511a This seems unintentional. Do you want me to delete your posts?
