### ISSUE TITLE
Increasing Fuzz Input Size

### ISSUE THREAD

**Issue by l0s** [CodeIntelligenceTesting/jazzer#427]
What is the right way to increase the input size?

Similar to the [example in the README](https://github.com/CodeIntelligenceTesting/jazzer/blob/9187660732a99ffc982795bd121637a0339a0b23/README.md?plain=1#L130), I see the log message:

    INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes

In addition, when calling `FuzzedDataProvider::consumeBytes(int)`, I get fewer bytes than requested. Per the documentation, this is because the input size is not sufficiently long. The command I'm executing looks like this:

    /tmp/not-out/tmpzysle9uu/jazzer_driver --agent_path=/tmp/not-out/tmpzysle9uu/jazzer_agent_deploy.jar --cp=/tmp/not-out/tmpzysle9uu/myapp.jar:/tmp/not-out/tmpzysle9uu/myfuzzer.jar --target_class=MyFuzzer --jvm_args=-Xmx2048m:-Djava.awt.headless=true -max_len=8192 --alsologtostderr=true -rss_limit_mb=2560 -timeout=25 -seed=1337 -runs=4

In case it's relevant, `jazzer_driver` is being called through [oss-fuzz](https://github.com/google/oss-fuzz/).

**Comment by fmeum** [comment]
I am able to reproduce this issue, but am still pretty clueless as to the root cause. I don't think there is anything obviously wrong in `FuzzedDataProvider`. I will take a deeper look.

**Comment by fmeum** [comment]
I can reproduce this even with `-len_control=0`, but it no longer reproduces with `-mutation_depth=100`.

My best guess is that without any coverage feedback, a large input size can only be reached if it can be attained from an existing corpus input within a single mutation chain (default length of 5 individual mutations). Individual mutations are limited in the length delta they can cause, e.g. [sequences of random bytes are capped at length 128](https://github.com/llvm/llvm-project/blob/59351fe340f20a605bae53260ed30a8e0fd95cb6/compiler-rt/lib/fuzzer/FuzzerMutate.cpp#L147).

@l0s Could you check whether this goes away if you add a corpus entry that has the required size?

**Comment by l0s** [comment]
@fmeum can you share documentation on how to add a corpus entry? It was not clear to me how to do that.

**Comment by fmeum** [comment]
oss-fuzz requires you to add files to a directory next to your fuzz test: https://google.github.io/oss-fuzz/getting-started/new-project-guide/#seed-corpus.

Usually, this is one by [downloading the corpus in the Dockerfile](https://github.com/google/oss-fuzz/blob/901fc681121a4e590487062ef46d5f4619b86da5/projects/apache-commons/Dockerfile#L35) and then [moving it into the correct location in `build.sh`](https://github.com/google/oss-fuzz/blob/901fc681121a4e590487062ef46d5f4619b86da5/projects/apache-commons/build.sh#L19).

Feel free to reopen if you should encounter problems getting this set up.
