### ISSUE TITLE
JUnit source JAR on Maven Central is invalid

### ISSUE THREAD

**Issue by gredler** [CodeIntelligenceTesting/jazzer#474]
The new JUnit integration is awesome, but it looks like the source JAR uploaded to Maven Central (jazzer-junit-0.12.0-sources.jar) is invalid. My IDE (Eclipse) is unable to use it to browse the sources, and 7Zip is unable to open it (which is usually possible).

**Comment by fmeum** [comment]
I am planning to figure out how to build a proper source JAR and also add documentation for the new integration. Happy to hear you already figured it out though :-)
