### ISSUE TITLE
Introduce JDK 17 in OSS Fuzz

### ISSUE THREAD

**Issue by asomov** [CodeIntelligenceTesting/jazzer#484]
I tried to[ upgrade JDK to 17 in OSS Fuzz](https://github.com/google/oss-fuzz/pull/8479)

Unfortunately, Jazzer expects[ JDK 15 and it fails](https://github.com/google/oss-fuzz/actions/runs/3044449831/jobs/4904851651
)

With this error:

```
ERROR: /src/jazzer/agent/src/main/java/com/code_intelligence/jazzer/agent/BUILD.bazel:3:15: While resolving toolchains for target //agent/src/main/java/com/code_intelligence/jazzer/agent:agent_lib: no matching toolchains found for types @bazel_tools//tools/jdk:runtime_toolchain_type
ERROR: Analysis of target '//agent:jazzer_agent_deploy.jar' failed; build aborted: 
```

Can you please help to find out what can I  do to change Jazzer to work with JDK 17 in OSS Fuzz ?

**Comment by asomov** [comment]
@fmeum Well, OSS Fuzz clones this project and checks out a specific commit.

**Comment by fmeum** [comment]
It's in this repo (OSS-Fuzz): https://github.com/snakeyaml/oss-fuzz/blob/a6cc50a6150859cda674951e44df6c6940ef1af2/infra/base-images/base-builder/install_java.sh#L33
You change the first part of it in this PR, but not the second part that contains the command to build Jazzer from the checked out commit. We do test Jazzer with JDK 17, so I would expect it to work.

**Comment by asomov** [comment]
Sorry. Thank you for the support.
