### ISSUE TITLE
How to attach JVM debugger while reproducing fuzzer inputs?

### ISSUE THREAD

**Issue by bstee615** [CodeIntelligenceTesting/jazzer#522]
Hello, I've written a utility to print program values at function entry using Java Debug Interface. I want to run my utility while reproducing inputs generated by Jazzer. Normally I will run my utility by running the target program with the JVM options `-Dagentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=8787`, then connecting my utility to port 8787.

I see that with Jazzer, fuzzed inputs can be reproduced with `jazzer --cp=fuzz_target.jar:lib1.jar:lib2.jar --target_class=com.example.MyFirstFuzzTarget <optional_corpus_dir>`, but this does not let me supply arguments to the JVM in the way I am used to, and I cannot figure out how to attach my debugging tool to the JVM.

How can I attach my JVM debugger while reproducing fuzzer inputs with Jazzer's driver?

**Comment by fmeum** [comment]
You can pass JVM arguments to Jazzer's native launcher via `--jvm_args` (requires escaping `:` as `\:` though) or the `JAVA_OPTS` environment variable.

**Comment by bstee615** [comment]
Ok I see the relevant documentation in the README. Thank you!
