### ISSUE TITLE
Problem with docker image?

### ISSUE THREAD

**Issue by stephengardiner** [CodeIntelligenceTesting/jazzer#524]
Hi,

I'm having an issue trying to use the docker image. It probably me, because I'm new to jazzer and a docker novice, in many ways.  I detailed it here:

[Stackoverflow](https://stackoverflow.com/questions/74338191/cifuzz-jazzer-docker-image-missing-a-jar)

though perhaps I should have come here first.

Happily open to accept my "Doh!" moment, when you point out the obvious.

Thanks.

**Comment by fmeum** [comment]
Thanks for the detailed SO report! We made a lot of changes under the hood over the last weeks and missed that this also affected the Docker image.

https://github.com/CodeIntelligenceTesting/jazzer/pull/525 should fix this. I pushed a new image based on it.
