### ISSUE TITLE
Java Jazzer class seams to does not honor the --jvm_args nor JAVA_OPTS

### ISSUE THREAD

**Issue by AndreasTu** [CodeIntelligenceTesting/jazzer#529]
When using the new Java-Style `com.code_intelligence.jazzer.Jazzer` main. 
The code seams to not honor JVM options, which should be passed to child processes either with `--jvm_args` or `JAVA_OPTS`.

I could not find any code except of the Native launcher to check for these arguments.
In the Jazzer class the method  `javaBinaryArgs()` constructs the JVM args, but it does not copy the args into it.

**Comment by fmeum** [comment]
The Jazzer class runs in an existing JVM, so it is too late for it to configure the JVM. But it should preserve all JVM options when launching child processes, so using `JAVA_TOOL_OPTIONS` or just adding the JVM flags to the `java` invocation that starts Jazzer should work.

The docs on that will be improved soon, but we hope that this brings Jazzer more in line with well-known JVM workflows.

**Comment by AndreasTu** [comment]
Yes the first thing is understandable. I only would liked to change the JVM args of the spawned child processes.

And yes with `JAVA_TOOL_OPTIONS` it is working.

**Comment by fmeum** [comment]
Could you provide an example of JVM args provided on the command-line that aren't passed on to child processes? I would view that as a bug, it shouldn't be necessary to use `JAVA_TOOL_OPTIONS` for that.

**Comment by AndreasTu** [comment]
Root-Process:
-------------------
```
java.exe 
-classpath 
myProject.jar;jazzer-0.13.0.jar;jazzer-api-0.13.0.jar 
com.code_intelligence.jazzer.Jazzer
--jvm_args=-Dcom.vector.afb.comp.appl.impl.DefaultIncludes.includes=D:\dev\AFB\afb-compiler\subprojects\frontend\com.vector.afb.comp.frontend.impl\src\main\afl;-Dcom.vector.afb.comp.frontend.impl.func.SleepFunction.disabled=true;-Dfile.encoding=UTF-8 
--instrumentation_includes=com.vector.afb.** 
--target_class=com.vector.afb.comp.jazzer.test.CompileJazzerTest 
-use_value_profile=1 -rss_limit_mb=4096 -jobs=16 
--keep_going=10 
-dict=D:\dev\AFB\afb-compiler\subprojects\appl\com.vector.afb.comp.jazzer.test\src\dict\dictionary.txt 
-runs=-1 D:\dev\AFB\afb-compiler\subprojects\appl\com.vector.afb.comp.jazzer.test\build\jazzerCorpus D:\dev\AFB\afb-compiler\subprojects\appl\com.vector.afb.comp.jazzer.test\build\tmp\jazzerInputCorpus
```

Child-Process:
-------------------
```
"java.exe"  
"-cp" 
"myProject.jar;jazzer-0.13.0.jar;jazzer-api-0.13.0.jar" 
"-Djdk.attach.allowAttachSelf=true" 
"com.code_intelligence.jazzer.Jazzer" 
"--jvm_args=-Dcom.vector.afb.comp.appl.impl.DefaultIncludes.includes=D:\dev\AFB\afb-compiler\subprojects\frontend\com.vector.afb.comp.frontend.impl\src\main\afl;-Dcom.vector.afb.comp.frontend.impl.func.SleepFunction.disabled=true;-Dfile.encoding=UTF-8" 
"--instrumentation_includes=com.vector.afb.**" 
"--target_class=com.vector.afb.comp.jazzer.test.CompileJazzerTest" 
"-use_value_profile=1" 
"-rss_limit_mb=4096" 
"--keep_going=10" 
"-dict=D:\dev\AFB\afb-compiler\subprojects\appl\com.vector.afb.comp.jazzer.test\src\dict\dictionary.txt" 
"-runs=-1" "D:\dev\AFB\afb-compiler\subprojects\appl\com.vector.afb.comp.jazzer.test\build\jazzerCorpus" "D:\dev\AFB\afb-compiler\subprojects\appl\com.vector.afb.comp.jazzer.test\build\tmp\jazzerInputCorpus" 
"--id_sync_file=D:\TEMP\jazzer-5494348125502420875"
```

**Comment by fmeum** [comment]
Could you try passing the JVM args directly to `java.exe` before the main class, instead of using `--jvm_args=`? The latter has always been a clutch that isn't necessary anymore with the new approach.

**Comment by AndreasTu** [comment]
Yes that is working fine. Good to know. That will solve my issue.

Btw thanks for the great tooling. It found many bugs in my Project :) .

**Comment by fmeum** [comment]
Glad to hear that! Happy fuzzing!
