### ISSUE TITLE
How to find collected data

### ISSUE THREAD

**Issue by GanbaruTobi** [CodeIntelligenceTesting/jazzer#530]
Hi,

I run my fuzzer with

`bazel run //examples:NeethiPolicyFuzzer -- /home/gbaru/code/fuzzer/jazzer/examples/input` 

The generated output is:

`
...
== Java Exception: java.lang.IllegalArgumentException: service is not a <wsp:Policy> element.
	at org.apache.neethi.PolicyBuilder.getPolicyOperator(PolicyBuilder.java:176)
	at org.apache.neethi.PolicyBuilder.getPolicy(PolicyBuilder.java:113)
	at org.apache.neethi.PolicyBuilder.getPolicy(PolicyBuilder.java:99)
	at org.apache.neethi.PolicyEngine.getPolicy(PolicyEngine.java:78)
	at com.example.NeethiPolicyFuzzer.fuzzerTestOneInput(NeethiPolicyFuzzer.java:19)
DEDUP_TOKEN: 53578f7fc4051ac1
== libFuzzer crashing input ==
MS: 0 ; base unit: 0000000000000000000000000000000000000000

artifact_prefix='/home/gbaru/.cache/bazel/_bazel_gbaru/a0479a67e61f3c869908bb9821663bb2/execroot/jazzer/bazel-out/k8-opt/testlogs/examples/NeethiPolicyFuzzer/test.outputs/'; Test unit written to /home/gbaru/.cache/bazel/_bazel_gbaru/a0479a67e61f3c869908bb9821663bb2/execroot/jazzer/bazel-out/k8-opt/testlogs/examples/NeethiPolicyFuzzer/test.outputs/crash-b7a277d1941569e326f379db3a8c23e9978bbeda

reproducer_path='/home/gbaru/.cache/bazel/_bazel_gbaru/a0479a67e61f3c869908bb9821663bb2/execroot/jazzer/bazel-out/k8-opt/testlogs/examples/NeethiPolicyFuzzer/test.outputs'; Java reproducer written to /home/gbaru/.cache/bazel/_bazel_gbaru/a0479a67e61f3c869908bb9821663bb2/execroot/jazzer/bazel-out/k8-opt/testlogs/examples/NeethiPolicyFuzzer/test.outputs/Crash_b7a277d1941569e326f379db3a8c23e9978bbeda.java
`

But none of these files exist:

'
cat: /home/gbaru/.cache/bazel/_bazel_gbaru/a0479a67e61f3c869908bb9821663bb2/execroot/jazzer/bazel-out/k8-opt/testlogs/examples/NeethiPolicyFuzzer/test.outputs/crash-b7a277d1941569e326f379db3a8c23e9978bbeda: No such file or directory
'

Is this a bug? What is the way to collect crashes?

Thx

**Comment by fmeum** [comment]
Bazel zips up the test outputs after the run, so you should be seeing a zip in the testlogs directory corresponding to the test.

That said, `java_fuzz_test` is more of a way for us to offer ready made examples than a supported way to fuzz real targets. I would recommend using either the command-line interface or, if you want good Bazel support, rules_fuzzing.

**Comment by GanbaruTobi** [comment]
Thanks for the feedback.

I didn't find any zip in the testlogs directory. I assume the command-line interface mentioned is ./jazzer.
When running the following line i got a crash and reproducer (unzipped) in the launching directory:
`./jazzer --cp=./examples/NeethiPolicyFuzzer_target_deploy.jar --target_class=com.example.NeethiPolicyFuzzer`

I will look into the rules_fuzzing, thanks for suggesting
