### ISSUE TITLE
Can you push 0.13.1 to Maven Central please?

### ISSUE THREAD

**Issue by stephengardiner** [CodeIntelligenceTesting/jazzer#535]
Hi folks,

Trying to setup some fuzzing on my project (with the hope that I can write a presentation for our developer community) and there seems to be some significant changes in this version.

Please push to Maven Central, when you get the opportunity.

Best regards,
Stephen Gardiner

**Comment by fmeum** [comment]
The changes in 0.13.1 that affect the Maven version are very minor, the big bugfix that caused the patch release only affects the standalone jar that's part of the GitHub releases.

I will push 0.13.1 to Maven, but you can safely use 0.13.0.

**Comment by fmeum** [comment]
I pushed 0.13.1, it should be on Maven Central in a few hours.
