### ISSUE TITLE
use jazzer_standalone.jar  alone, Could not find or load main class 

### ISSUE THREAD

**Issue by t1ucky** [CodeIntelligenceTesting/jazzer#536]
I tried to run jazzer_standalone.jar(v0.13.1) on macos_arm64 ,but have some thing wrong,Terminal report:
```
$ java -jar jazzer_standalone.jar
Error: Could not find or load main class com.code_intelligence.jazzer.jazzer_standalone
```

**Comment by fmeum** [comment]
Please use the `jazzer` executable next to it in the release archive to launch Jazzer. 

I'll add the ability to launch the jar directly as well. If you don't want to use a native binary, you can already use `com.code-intelligence:jazzer:0.13.1` (with its dependencies) in this way.
