### ISSUE TITLE
Junit jupiter not picking up any "jazzer" tagged tests

### ISSUE THREAD

**Issue by stephengardiner** [CodeIntelligenceTesting/jazzer#539]
Hi,

I'm trying to retrofit Jazzer to an existing project (often a mistake!), just to get some familiarity with the software. Having seen that the new Junit jupiter integration is in play, I thought I would try and use that.

So, I have a new fuzz test task in my gradle build script:
```
	val fuzzTest = task<Test>("fuzztest") {
		description = "Runs fuzz tests."
		group = "verification"

	dependsOn(tasks.compileTestJava)

	testClassesDirs = sourceSets["test"].output.classesDirs
	classpath = sourceSets["test"].runtimeClasspath + sourceSets.main.get().output
	useJUnitPlatform {
		includeTags("jazzer")
	}
	//shouldRunAfter("test")
}
```

 and I have tagged my fuzz test with the required tag (which is also included in the @FuzzTest annotation) 
```
@Tag("jazzer")
class ByteFuzzTest {
    @FuzzTest(maxDuration = "2m")
    void byteFuzz(byte[] data) {
        assumeFalse(System.getenv("JAZZER_FUZZ").isEmpty());
        if (data.length < 1) {
            return;
        }
        if (data[0] % 2 == 0) {
            fail();
        }
    }
}
```

with JAZZER_FUZZ=1, I always get this error message:
```
org.junit.platform.launcher.core.EngineDiscoveryOrchestrator lambda$logTestDescriptorExclusionReasons$7
INFO: 18 containers and 14 tests were excluded because tags do not match tag expression(s): [jazzer]
```

Probably my configuration or junit jupiter libraries, perhaps? I have these in my build script:
```
    testImplementation(group = "org.junit.jupiter", name = "junit-jupiter", version = "5.9.1")
    testImplementation(group = "org.junit.jupiter", name = "junit-jupiter-api", version = "5.9.1")
    testImplementation(group = "org.junit.jupiter", name = "junit-jupiter-params", version = "5.9.1")
    testImplementation(group = "com.code-intelligence", name="jazzer-junit", version="0.13.1")
```

Pretty sure this is on me, but any suggestions would be gratefully received.

**Comment by fmeum** [comment]
I edited your initial comment to fix the formatting: You have to use three backticks instead of just a single one to properly start and end a code block.

As far as I can tell, "tags" are a concept specific to the JUnit Jupiter engine. Jazzer fuzzing runs (`@FuzzTest` run with `JAZZER_FUZZ=1`) are backed by a custom test engine. We are looking into implementing it as part of Jupiter, which I assume would resolve this inconsistency (and others).

**Comment by fmeum** [comment]
I stand corrected, tags are a JUnit *platform* feature. Will look into adding support.

**Comment by fmeum** [comment]
@stephengardiner I just pushed v0.13.2 to Maven Central with a fix for this bug. It should become available in a couple hours. Please reopen this issue if the fix doesn't work for you.
