### ISSUE TITLE
`@FuzzTest` with `JAZZER_FUZZ=1` is not backed by JUnit Jupiter

### ISSUE THREAD

**Issue by stephengardiner** [CodeIntelligenceTesting/jazzer#543]
Firstly, thank you for fixing my formatting of the original issue (seems when you hit insert "Add code" in my browser you only get two backticks inserted - which I assumed you would put your code in-between 🙄 ).

I cannot reopen the original issue as you closed it and I didn't, and you, as collaborator trump me, which is obviously the correct state of affairs.

Also, apologies for not replying sooner, I had a crash on my bicycle the other night and narrowly avoided faceplanting the tarmac (I did hit my head but my helmet saved me from greater injury). Thus, I had a mild concussion and am a bit banged up, so had to curtail my extra curricular jazzer spelunking. 🤕 

Okay, so 0.13.2 gives us some improvement. With JAZZER_FUZZ not set, I get the same output:
```
Dec 02, 2022 7:35:55 PM org.junit.platform.launcher.core.EngineDiscoveryOrchestrator lambda$logTestDescriptorExclusionReasons$7
INFO: 18 containers and 14 tests were excluded because tags do not match tag expression(s): [jazzer]
```
So, it seems it doesn't pay attention to the tags, but obviously only picks up ```"@FuzzTest"``` tagged tests.

It does instrument the project and I suspect, as I haven't setup any resource input, it doesn't do anything for that reason. However right now, I'm more interested in using JAZZER_FUZZ=1 and when I do this I get the same error message above but it does start fuzzing, so thank you!

Something to look at though, especially from my perspective at this stage of jazzer integration and testing, is that your jazzer-specific junit engine doesn't respect the import ```org.junit.jupiter.api.Disabled``` annotation at neither the class level nor the individual test level. This is important because I might have a selection of jazzer tests that I have recorded output for, but then want to create a new jazzer test to stress another part of the api.

Is that possible?

_Originally posted by @stephengardiner in https://github.com/CodeIntelligenceTesting/jazzer/issues/539#issuecomment-1335676027_

**Comment by fmeum** [comment]
@stephengardiner That sounds rough, hope you recover soon!

Both the message you get and the fact that `@Disabled` isn't honored by `JAZZER_FUZZ=1` are a consequence of a deeper architectural problem that we are working on solving: While `@FuzzTest` with `JAZZER_FUZZ=0` is just a regular JUnit Jupiter `@ParameterizedTest`, with `JAZZER_FUZZ=1` it becomes a test backed by a custom test engine. In the latter case, it thus ignores all Jupiter-specific functionality.

I am working on fixing this by porting the fuzzing mode over to JUnit Jupiter. This is a bit tricky though, so I can't say yet how well it will work.
