### ISSUE TITLE
Jazzer junit test engine doesn't write the crash unit test file?

### ISSUE THREAD

**Issue by stephengardiner** [CodeIntelligenceTesting/jazzer#546]
Hi, me again.

So I'm running a Fuzz test through the junit engine and the output tells me:

```
<snip>
MS: 2 ShuffleBytes-InsertByte-; base unit: 0764e7ddb1c31bca059330ce28666718f0879fa2
0xa,0x3a,0xa,0x4a,
\012:\012J
artifact_prefix='\'; Test unit written to \crash-ba614fa5e4b1a1288b0086415b491891adece8b4
Base64: CjoKSg==
Done 62 runs in 0 second(s)
```
But I cannot find that file. I'm running in gradle under Intellij's IDEA.

Obviously, I've looked in the root of C: (running on Windows 10). I've also done a search for _"crash-"._ The corpus files appear, but nothing else.

If I'm being dumb again, I apologise.

**Comment by fmeum** [comment]
What is the working directory of your tests? The `artifact_prefix='\'` looks like a bug, but I'm not sure where it's coming from.

Please take a look at https://github.com/CodeIntelligenceTesting/jazzer/issues/521: We use a well-known directory and emit usage information using JUnit primitives, but apparently these are not printed by Gradle.

**Comment by ghostpepper108** [comment]
@fmeum - Any update on this. I am facing the same issue in IntelliJ IDEA. I created the directory as well after referring https://github.com/CodeIntelligenceTesting/jazzer/issues/521

 I am getting this but don't see any file

MS: 0 ; base unit: 0000000000000000000000000000000000000000
artifact_prefix='/'; Test unit written to /crash-da39a3ee5e6b4b0d3255bfef95601890afd80709
Base64: 
Done 1 runs in 0 second(s)

**Comment by fmeum** [comment]
I will look into why there are no files. I had problems reproducing this problem, but I will try again.

@ghostpepper108 The exception is expected: `data.consumeString(2)` may return strings that are shorter than two characters, including the empty string. If you don't expect the rest of your fuzz test to handle them gracefully, you can skip these inputs using JUnit's [assumptions](https://junit.org/junit5/docs/5.0.0/api/org/junit/jupiter/api/Assumptions.html) or simply by returning early.

**Comment by freedom1b2830** [comment]
maven
```
[INFO] --- maven-surefire-plugin:3.0.0-M7:test (default-test) @ test ---
[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.example.AutofuzzFuzzTest
[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.258 s - in com.example.AutofuzzFuzzTest
INFO: Loaded 120 hooks from com.code_intelligence.jazzer.runtime.TraceCmpHooks
INFO: Loaded 4 hooks from com.code_intelligence.jazzer.runtime.TraceDivHooks
INFO: Loaded 2 hooks from com.code_intelligence.jazzer.runtime.TraceIndirHooks
INFO: Loaded 4 hooks from com.code_intelligence.jazzer.runtime.NativeLibHooks
INFO: Loaded 8 hooks from com.code_intelligence.jazzer.sanitizers.Deserialization
INFO: Loaded 5 hooks from com.code_intelligence.jazzer.sanitizers.ExpressionLanguageInjection
INFO: Loaded 70 hooks from com.code_intelligence.jazzer.sanitizers.LdapInjection
INFO: Loaded 46 hooks from com.code_intelligence.jazzer.sanitizers.NamingContextLookup
INFO: Loaded 1 hooks from com.code_intelligence.jazzer.sanitizers.OsCommandInjection
INFO: Loaded 48 hooks from com.code_intelligence.jazzer.sanitizers.ReflectiveCall
INFO: Loaded 8 hooks from com.code_intelligence.jazzer.sanitizers.RegexInjection
INFO: Loaded 16 hooks from com.code_intelligence.jazzer.sanitizers.RegexRoadblocks
INFO: Loaded 19 hooks from com.code_intelligence.jazzer.sanitizers.SqlInjection
INFO: Instrumented com.example.AutofuzzFuzzTest (took 357 ms, size +19%)
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 2557698436
INFO: Loaded 1 modules   (512 inline 8-bit counters): 512 [0x7f243c99bf70, 0x7f243c99c170), 
INFO: Loaded 1 PC tables (512 PCs): 512 [0x7f243c563920,0x7f243c565920), 
INFO:        0 files found in /home/$USER/eclipse-workspace/test/.cifuzz-corpus/com.example.AutofuzzFuzzTest
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
INFO: A corpus is not provided, starting from an empty corpus
#2      INITED cov: 3 ft: 3 corp: 1/1b exec/s: 0 rss: 687Mb
MS: 5 ChangeByte-CrossOver-ChangeBit-ShuffleBytes-InsertByte-; base unit: adc83b19e793491b1c6ea0fd8b46cd9f32e592fc
0x3a,0x8,
:\010
artifact_prefix='/'; Test unit written to /crash-b151f9ef5cd315d2148e6fe8c5e69208eba30aef
Base64: Ogg=
Done 7 runs in 0 second(s)
[INFO] 
[INFO] Results:
[INFO] 
[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1
```

I allowed to write to / user.
jazzer wrote there only raw data to reproduce the error, without java code
![DeepinScreenshot_выберите-область_20221231110150](https://user-images.githubusercontent.com/102818470/210134450-5d43003e-ebb3-4c70-9485-b22bdb09b551.png)

**Comment by fmeum** [comment]
@stephengardiner @ghostpepper108 @freedom1b2830 I tested this again on Windows and can't reproduce the issue. Could one of you share a complete reproducer with me (e.g. as a git repo or an archive)?

**Comment by freedom1b2830** [comment]
@fmeum https://github.com/freedom1b2830/jazzer-todo

**Comment by fmeum** [comment]
Thanks, @freedom1b2830, I was able to reproduce it now and know how to fix it.
