### ISSUE TITLE
Issues with classpath for cifuzz/jazzer docker image

### ISSUE THREAD

**Issue by lukaswoellhaf** [CodeIntelligenceTesting/jazzer#563]
I cannot run the docker image with the provided command in the readme.
Following the command:
`docker run -v path/containing/the/application:/fuzzing cifuzz/jazzer --cp=<classpath> --target_class=<fuzz test class>`

I'm executing the command in the root directory of my project:
`docker run -v $(pwd):/fuzzing cifuzz/jazzer --cp=build/libs/jazzer-docker-example-1.0-SNAPSHOT-all.jar --target_class=com.example.FuzzTestCase`

But I'm getting:

```
ERROR: 'com.example.FuzzTestCase' not found on classpath:

build/libs/jazzer-docker-example-1.0-SNAPSHOT-all.jar:/app/jazzer_standalone.jar

All required classes must be on the classpath specified via --cp.
```

Is there something wrong, with how I provided the classpath? Hope someone can point out the obvious to me. Thanks : )

**Comment by fmeum** [comment]
That does look correct to me, assuming `build/libs/jazzer-docker-example-1.0-SNAPSHOT-all.jar` lives under `$(pwd)` and isn't a symlink that would fail to resolve in the container. There is no magic involved, Jazzer simply starts a JVM with the classpath provided via `--cp` and `jazzer_standalone.jar` appended to it.

You could try downloading a release archive and use the binary on your machine without docker.

**Comment by lukaswoellhaf** [comment]
Thanks 🙏 Will try to compile it locally - but for the long run this I want to set it up in a CI/CD Pipeline, so I think the Docker Image of course would be the easiest approach to this.

**Comment by fmeum** [comment]
Can you share how you built your `jazzer-docker-example-1.0-SNAPSHOT-all.jar`? If you have a project I can use to reproduce this on my machine, I can look into why it doesn't work.

**Comment by lukaswoellhaf** [comment]
Sure I uploaded an example project here: https://github.com/lukaswoellhaf/jazzer-docker-example.git

**Comment by fmeum** [comment]
I had to remove the `shadow` plugin to get the build commands to work.

Then, the jar generated by Gradle only contains the `main` classes, not the `test` classes. Could you try mounting `build/classes/java/test` into the container as well?

**Comment by lukaswoellhaf** [comment]
Removed the `shadow` plugin and tested the build. If you run `./gradlew build` it should build also the test classes. Also added the docker run command in the `README.md`
