### ISSUE TITLE
Differential Fuzzing using Jazzer

### ISSUE THREAD

**Issue by firhard** [CodeIntelligenceTesting/jazzer#564]
Hi,

I am quite new to Jazzer. I just want to ask if it's possible to create a fuzzer using Jazzer that'll use multiple programs (a new patch of the same program, as an example), and look at whether it gives the same/different output. The use case of this is to confirm that the behavior on both programs is the same.

Many thanks,
Firhard

**Comment by fmeum** [comment]
If by "multiple programs" you mean "multiple Java/Kotlin/... libraries" then yes, Jazzer would be a good choice for that.

With the JUnit 5 integration, a simple differential fuzz test could look like this:

```java
@FuzzTest
void differentialFuzzTest(FuzzedDataProvider data) {
  String input = data.consumeRemainingAsString();
  String output1 = SomeLib.process(input);
  String output2 = SomeLibWithPatch.process(input);

  assertEquals(output1, output2);
}
```
