### ISSUE TITLE
Does Jazzer use conclic execution?

### ISSUE THREAD

**Issue by H4de5-7** [CodeIntelligenceTesting/jazzer#571]
Hi, does Jazzer use conclic execution to find path?

**Comment by fmeum** [comment]
No, at the moment Jazzer only uses coverage Instrumentation and hooks on comparisons and standard library functions to inform its mutations.

If the code under test has more complicated comparisons, you can try to use value profiling (with the `-use_value_profile=1` argument or the `jazzer.valueprofile` property set to `true` for the JUnit integration). In this mode, Jazzer will track bitwise progress through comparisons.

**Comment by H4de5-7** [comment]
Thanks for your explanation!

**Comment by kyakdan** [comment]
@H4de5-7 Do you have specific use cases that the current state of Jazzer cannot handle? Here, it would be intersection to see whether we can improve Jazzer by including more signals from the program state into its feedback (See https://github.com/CodeIntelligenceTesting/jazzer/blob/main/examples/src/main/java/com/example/MazeFuzzer.java).

**Comment by H4de5-7** [comment]
Thanks, but I'm just curious how jazzer uses program information to guide mutations. And I think "value profile" looks like a good solution.
