### ISSUE TITLE
Can you publish 0.14.0 to maven central ?

### ISSUE THREAD

**Issue by freedom1b2830** [CodeIntelligenceTesting/jazzer#581]
Can you publish 0.14.0 to maven central ?

**Comment by fmeum** [comment]
Working on it, got a new laptop and have to figure out GPG again :-)

**Comment by freedom1b2830** [comment]
If you have linux.My setup for such features:
1.gpg as ssh-agent (authorization with git clone||push and others)
2.code signature on commit, tags
3.show signatures on "git log"

highlights:
a)1027 is uid user "id -u"
b)A2FF043202D1EF3100B9AF3E60C13AF3976A04D4 it gpg key id (keygrip)
c)for signing, this setting below will do, for authorization you need to log in to the user through the tty console (OR change the path in the OR_CHANGE_IT LABEL)
it has to do with how systemd and systemd-login work
when accessing via tty, the path ``/run/user/$(id -u)/`` is created


cat .ssh/config 
``IdentityAgent /run/user/1027/gnupg/S.gpg-agent.ssh``
``IdentityAgent OR_CHANGE_IT``

cat .gnupg/gpg-agent.conf 
``enable-ssh-support``

cat .gnupg/gpg.conf 
``use-agent``

cat .gnupg/sshcontrol |grep -v "#"
``A2FF043202D1EF3100B9AF3E60C13AF3976A04D4``

gpg --with-keygrip -k
```
.....
sub   rsa4096 2022-04-02 [SEA]
      Keygrip = A2FF043202D1EF3100B9AF3E60C13AF3976A04D4
....
```


cat .bashrc |grep -v "#"|uniq
```
unset SSH_AGENT_PID
if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
  export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
  
  export SSH_AUTH_SOCK=OR_CHANGE_IT
fi
export GPG_TTY=$(tty)
gpg-connect-agent updatestartuptty /bye >/dev/null
```

cat .gitconfig 
```
[init]
        defaultBranch = main
[user]
        name = freedom1b2830
        email = freedom1b2830@gmail.com
        signingKey = 149B28A256037AF6AD0C1EC9102E68A691AFEA9F
[commit]
        gpgSign = true
[tag]
        gpgSign = true
[log]
        showSignature = true
```

**Comment by fmeum** [comment]
We keep our private keys on smart cards, which work very well except when you set them up for the first time on a new machine. I added a description of our setup to the docs for the next time someone has to go through this.

Version 0.14.0 is now up on Maven.
