### ISSUE TITLE
Java reproducer fails to reproduce

### ISSUE THREAD

**Issue by stephenWebComm** [CodeIntelligenceTesting/jazzer#589]
Use [Sample](https://github.com/CodeIntelligenceTesting/jazzer#quick-start)
```
docker run -it cifuzz/jazzer-autofuzz \
   com.mikesamuel:json-sanitizer:1.2.0 \
   com.google.json.JsonSanitizer::sanitize \
   --autofuzz_ignore=java.lang.ArrayIndexOutOfBoundsException
```
is not reproduced by

```
java -cp json-sanitizer-1.2.0.jar Crash_26632fabd7e32ef4330341f12e3b344f79baa26f.java
```

[Crash_26632fabd7e32ef4330341f12e3b344f79baa26f.txt](https://github.com/CodeIntelligenceTesting/jazzer/files/10358426/Crash_26632fabd7e32ef4330341f12e3b344f79baa26f.txt)

**Comment by stephenWebComm** [comment]
thanks for help !

**Comment by fmeum** [comment]
@stephenWebComm I just built and pushed a new Docker image.
