### ISSUE TITLE
Question:fuzzing/debugging multiple applications at once

### ISSUE THREAD

**Issue by freedom1b2830** [CodeIntelligenceTesting/jazzer#636]
Is it possible to send requests from one application and catch exceptions in another?

There are 2 applications:
1) sender (senderApp) - code completely written by me (maven, java-jar)
2) server application (targetApp) - not my code, I can only run it through java -jar targetApp.jar
I need the 2nd application to go through its main launch cycle, I can track it with the help of the plugin (send a request at the end of the launch)

Java agents are suitable for fuzzing
![jazzer-remote](https://user-images.githubusercontent.com/102818470/219881891-42c0c76b-d5e6-4969-99f0-0f0bc5a0411a.svg)

**Comment by bertschneider** [comment]
Jazzer can only track executions and errors inside of one JVM.

Code Intelligence offers a product, called [Web API Fuzzing](https://docs.code-intelligence.com/java-web-api-fuzzing), that may fit your requirements, though.

**Comment by freedom1b2830** [comment]
Unfortunately this is not a web app.
