### ISSUE TITLE
v0.9.1 does not build on OSX

### ISSUE THREAD

**Issue by eustas** [CodeIntelligenceTesting/jazzer#64]
Bazel output:
```
ERROR: /clients/jazzer/third_party/jni/BUILD.bazel:44:10: no such target '@local_jdk//:lib/server/libjvm.so': target 'lib/server/libjvm.so' not declared in package '' defined by /private/var/tmp/_bazel_eustas/576d75f9d51a861dc30c748efc340c9f/external/local_jdk/BUILD.bazel and referenced by '//third_party/jni:libjvm'
ERROR: Analysis of target '//third_party/jni:libjvm' failed; build aborted: Analysis failed
```

**Comment by fmeum** [comment]
macOS support is not yet included in any release (there are also no release binaries for it), but it should work on `main`. Given that you filed #65, can I assume it also works for you?

**Comment by eustas** [comment]
Correct.

**Comment by eustas** [comment]
Given that osx is mentioned in "using" section in readme I was under impression it is supported (builds on some release).

Nevermind, feel free to close this bug.

**Comment by ShindeAkshay** [comment]
@eustas How did you solved this issue? I am also getting similar error on macOS while running bazel
`@local_jdk//:lib/server/libjvm.dylib': target 'lib/server/libjvm.dylib' not declared in package '' (did you mean 'jre/lib/server/libjvm.dylib'?) defined by /private/var/tmp/_bazel_aksshind/e18a639a288529326df8bafcc10cf2af/external/local_jdk/BUILD.bazel and referenced by '//third_party/jni:libjvm_osx'`
