### ISSUE TITLE
How to exclude system hook

### ISSUE THREAD

**Issue by liukoo** [CodeIntelligenceTesting/jazzer#659]
such as OsCommandInjection, I want to disable this hook 

https://github.com/CodeIntelligenceTesting/jazzer/blob/main/sanitizers/src/main/java/com/code_intelligence/jazzer/sanitizers/OsCommandInjection.kt

**Comment by fmeum** [comment]
You can disable individual hooks with `--disabled_hooks`, see https://github.com/CodeIntelligenceTesting/jazzer/blob/8806842cd74b60cb276ec77b4db6d0e324bdc689/tests/BUILD.bazel#L181 for an example.
