### ISSUE TITLE
How to work with scanner in code depth?

### ISSUE THREAD

**Issue by freedom1b2830** [CodeIntelligenceTesting/jazzer#663]
I need to get to this place and not manually write to the console.

stacktrace like this:
main->method1(arg1,arg2,arg3)

```java
void method1(int arg1,int arg2,int arg3){
   Scanner scanner =new java.util.Scanner(System.in)
   line=scanner.readLine();
   if(line.equals(Integer.toString(arg1))){
    //ok
    }else if (line.equals(Integer.toString(arg2))){
    //error
    }else if (line.equals(Integer.toString(arg3))){
    //ok
    }
}
```

**Comment by fmeum** [comment]
Could you explain in more detail how this relates to Jazzer? I can't really tell what you want to achieve and what doesn't work.

**Comment by freedom1b2830** [comment]
I need to receive a string instead of requesting it from the console
```String line=scanner.readLine();``` change to ```String line="fuzzdata1..."```
every time the method1 function is called
(I need to replace the Scanner::readLine call with a line from jazzer)

keeping in mind that the arguments are equal
```arg1=1;
arg3=2;
arg3=3;
```

function call # 1
```java
void method1(int arg1,int arg2,int arg3){
   Scanner scanner =new java.util.Scanner(System.in)
  String line="fuzzdata1"
   if(line.equals(Integer.toString(arg1))){
    //ok
    }else if (line.equals(Integer.toString(arg2))){
    //error
    }else if (line.equals(Integer.toString(arg3))){
    //ok
    }
}
```


function call # 2
```java
void method1(int arg1,int arg2,int arg3){
   Scanner scanner =new java.util.Scanner(System.in)
  String line="fuzzdata192е"
   if(line.equals(Integer.toString(arg1))){
    //ok
    }else if (line.equals(Integer.toString(arg2))){
    //error
    }else if (line.equals(Integer.toString(arg3))){
    //ok
    }
}
```

function call # 3
```java
void method1(int arg1,int arg2,int arg3){
   Scanner scanner =new java.util.Scanner(System.in)
  String line="1"
   if(line.equals(Integer.toString(arg1))){
    //ok
    }else if (line.equals(Integer.toString(arg2))){
    //error
    }else if (line.equals(Integer.toString(arg3))){
    //ok
    }
}
```
function call # 4 EXCEPTION
```java
void method1(int arg1,int arg2,int arg3){
   Scanner scanner =new java.util.Scanner(System.in)
  String line="2"
   if(line.equals(Integer.toString(arg1))){
    //ok
    }else if (line.equals(Integer.toString(arg2))){
    //error
    }else if (line.equals(Integer.toString(arg3))){
    //ok
    }
}
```

**Comment by freedom1b2830** [comment]
This solution is suitable if:
1)In the code (to repeat the error) there will be data from this stream.
2)Make it like a hook

**Comment by fmeum** [comment]
As @bertschneider mentioned above, you can use `System.setIn(new ByteArrayInputStream(data.consumeBytes(1000))` or some variant thereof to have any part of the code that reads from stdin read fuzzed data instead. There shouldn't be a need to introduce a hook for this.

Please reopen if you think that this doesn't address your use case.
