### ISSUE TITLE
Crash only hs_err_pid

### ISSUE THREAD

**Issue by freedom1b2830** [CodeIntelligenceTesting/jazzer#666]
Unfortunately, I don't know how to configure coredump persistence for java applications (/usr/lib/systemd/systemd-coredump).
only this log remains:
[FUZZER_hs_err_pid47418.log](https://github.com/CodeIntelligenceTesting/jazzer/files/10973565/FUZZER_hs_err_pid47418.log)

This is a single crash.
os:
Linux archlinux 6.2.5-arch1-1 # 1 SMP PREEMPT_DYNAMIC Sat, 11 Mar 2023 14:28:13 +0000 x86_64 GNU/Linux

```sh
/usr/lib/jvm/java-19-openjdk/bin/ принадлежит jdk-openjdk 19.0.2.u7-2
...


/usr/lib/ld-linux-x86-64.so.2 принадлежит glibc 2.37-2
/usr/lib/libcap.so.2.67 принадлежит libcap 2.67-1
/usr/lib/libc.so.6 принадлежит glibc 2.37-2
/usr/lib/libdl.so.2 принадлежит glibc 2.37-2
/usr/lib/libgcc_s.so.1 принадлежит gcc-libs 12.2.1-2
/usr/lib/libm.so.6 принадлежит glibc 2.37-2
/usr/lib/libnss_myhostname.so.2 принадлежит systemd-libs-selinux 253.1-3
/usr/lib/libnss_mymachines.so.2 принадлежит systemd-libs-selinux 253.1-3
/usr/lib/libnss_resolve.so.2 принадлежит systemd-libs-selinux 253.1-3
/usr/lib/libpthread.so.0 принадлежит glibc 2.37-2
/usr/lib/librt.so.1 принадлежит glibc 2.37-2
/usr/lib/libstdc++.so.6.0.30 принадлежит gcc-libs 12.2.1-2
/usr/lib/libz.so.1.2.13 принадлежит zlib 1:1.2.13-2
/usr/lib/systemd/systemd-coredump принадлежит systemd-selinux 253.1-3
/usr/share/locale/ru/LC_MESSAGES/libc.mo принадлежит glibc 2.37-2
```

**Comment by fmeum** [comment]
The log shows that `org.joml.Vector3f` performs an out-of-bounds read on a (presumably too short) `ByteBuffer` using `Unsafe`, which causes a segfault. https://github.com/JOML-CI/JOML/wiki/Design#java-nio-buffers advises against using Unsafe with non-direct `ByteBuffer`s.
