### ISSUE TITLE
Use custom corpus

### ISSUE THREAD

**Issue by liukoo** [CodeIntelligenceTesting/jazzer#673]
How to use user custom corpus file

**Comment by fmeum** [comment]
When you run Jazzer [from the command line](https://github.com/CodeIntelligenceTesting/jazzer#github-releases), just add a path to a file or directory with corpus entries as a positional argument.

In fact, Jazzer supports all libFuzzer arguments, so you can also take a look at [its documentation](https://llvm.org/docs/LibFuzzer.html) to learn more about specifying corpus directories.

(Feel free to reopen with more details if that shouldn't answer your question)
