### ISSUE TITLE
Use Jazzer with private Maven repository.

### ISSUE THREAD

**Issue by dmgping** [CodeIntelligenceTesting/jazzer#682]
All my jars are stored in a private maven repo, to avoid mounting my project to the docker container everytime I want to fuzz, how can I pass jazzer a repo location from which to pull jar files?

**Comment by freedom1b2830** [comment]
# (I'm not a jazzer developer)!
## For already downloaded jar files
## Project written and tested on linux (only)
Good day.
i have a project that uses a jar file in a directory. Gets class signatures and starts jazzer with these targets

repo https://github.com/publicLibs/continuous-Jazzer
build ``mvn clean install``

## Run:
```sh
java -jar continuousJazzer-agent-main-SNAPSHOT-jar-with-dependencies.jar LIST dir/with/jar
```
1) The program looks for jar files
2) Get signatures
3) Writes to the config

```sh
java -jar continuousJazzer-agent-main-SNAPSHOT-jar-with-dependencies.jar FUZZ config.yaml
```
1)Creates jazzer start arguments
2)Starts
## latest release
https://github.com/publicLibs/continuous-Jazzer/releases/tag/jazzer-0.16.1-format_pom

**Comment by bertschneider** [comment]
I assume you're referring to `cifuzz/jazzer-autofuzz`, correct? That image uses [Coursier](https://get-coursier.io/) to fetch dependencies and external repositories can be configured through the available Coursier [repository settings](https://get-coursier.io/docs/other-repositories). Something like:

```
docker run -e "COURSIER_REPOSITORIES=https://my.re.po -it cifuzz/jazzer-autofuzz [...]
``` 

Does this help?

**Comment by fmeum** [comment]
Please open a new issue if https://github.com/CodeIntelligenceTesting/jazzer/issues/682#issuecomment-1498690104 didn't help.
