### ISSUE TITLE
How to mutate to a specific value？

### ISSUE THREAD

**Issue by yongxin3344520** [CodeIntelligenceTesting/jazzer#747]
```
   @FuzzTest
    public void fuzzTest1(FuzzedDataProvider data) {
        String input = data.consumeRemainingAsString();
        if ("administrator".equals(input)){
            throw  new RuntimeException();
        }
   }
```

How did the above code change to the "Administrator" value? 
Where is the source code for its working principle?
Thanks ！

**Comment by fmeum** [comment]
There are two different parts of Jazzer at play here:

1. [`FuzzedDataProvider`](https://github.com/CodeIntelligenceTesting/jazzer/blob/main/src/main/java/com/code_intelligence/jazzer/driver/FuzzedDataProviderImpl.java) converts the bytes obtained from the fuzzer into a string.
2. Instrumentation applied to the Java byte code of your fuzz test reports a comparison of that string against `"administrator"` to Jazzer, which in turn translates this into a hint for the fuzzer to generate that particular string. The relevant parts are in https://github.com/CodeIntelligenceTesting/jazzer/blob/main/src/main/java/com/code_intelligence/jazzer/runtime/TraceDataFlowNativeCallbacks.java and https://github.com/CodeIntelligenceTesting/jazzer/blob/be1a7e56d71d4d8dfe71c08f216e0314b4c2f6e6/src/main/java/com/code_intelligence/jazzer/runtime/TraceCmpHooks.java#L81.
