### ISSUE TITLE
Build issue on Mac

### ISSUE THREAD

**Issue by br-lewis** [CodeIntelligenceTesting/jazzer#777]
I noticed that, on Mac, `bazel build //src/main/native/com/code_intelligence/jazzer/android:jvmti_h --verbose_failures` results in an error

```
base64: invalid argument bazel-out/darwin_arm64-opt/bin/src/main/native/com/code_intelligence/jazzer/android/jvmti.encoded
Usage:	base64 [-hDd] [-b num] [-i in_file] [-o out_file]
  -h, --help     display this message
  -Dd, --decode   decodes input
  -b, --break    break encoded string into num character lines
  -i, --input    input file (default: "-" for stdin)
  -o, --output   output file (default: "-" for stdout)
```

The issue is the classic difference between GNU and BSD coreutils. Changing [this line](https://github.com/CodeIntelligenceTesting/jazzer/blob/77749557f7ff20eb63b9867c86a7392d40415c0a/src/main/native/com/code_intelligence/jazzer/android/BUILD.bazel#L20) to
```
base64 --decode < $< > $(OUTS)
```
or
```
base64 --decode -i $< > $(OUTS)
```
fixes the problem.

The strange thing is that CI passes even on the Mac machines so that's something I want to investigate. But first I wanted to ask @TheCoryBarker is this intended to work on Macs as well or only Linux? I see the build rule in `SKIP_ON_WINDOWS` but if this only needs to work on Linux, that'll save some time.

**Comment by fmeum** [comment]
The Android targets are tagged as `manual` and thus only built when explicitly requested, which happens for Linux here: https://github.com/CodeIntelligenceTesting/jazzer/blob/336f059224fd1c3e28de9ca030d0d1271dae399f/.github/workflows/run-all-tests.yml#L42

The difference between macOS and Linux can be worked around by making the `cmd` of the genrule a `select({"@platforms//os/macos": "...", "@platforms//os/linux": "..."})`.

**Comment by br-lewis** [comment]
Thanks! Though you should really be ignoring work stuff right now 🙃 

The thing I'm finding strange is that this happens for me locally with `bazel build //...`. I don't think I have anything configured that would cause it to try to build it locally but not on the CI Macs. Though I guess I can just fix the command and have it work no matter what.

**Comment by TheCoryBarker** [comment]
I think it was wrong for me to set SKIP_ON_WINDOWS for Android build targets. I add another option in ```compat.bzl``` for ANDROID_ONLY. I think these options should be set for constraining the *target* you are building for, but not the host machine you are building on, correct me if I'm wrong though.

This will make it so the targets will try to build whenever you set ```--config=android_arm```, regardless of host machine, and be skipped whenever you don't set config to android_arm (or if you are build on an Android device I guess, unlikely)

This wont fix Brians issue though. Unfortunately the value will be always be ```@platforms//os:android``` so we can't use a select for the command. To fix this I also added a check in the starlark code to check for linux when building for Android. The PR is linked below, let me know what you think.

I'll also add, support for Mac should be possible if we can fix the select, but for Windows the android_binary/android_library build modules aren't supported. I am also confused why it is trying to build for you with ```bazel build //...``` though

PR:
https://github.com/CodeIntelligenceTesting/jazzer/pull/780
