### ISSUE TITLE
Released Jazzer 0.20.0 Jar on Maven is broken

### ISSUE THREAD

**Issue by AndreasTu** [CodeIntelligenceTesting/jazzer#836]
The released Jazzer Jar `com.code-intelligence:jazzer:0.20.0` is not a valid Jar anymore.
It contains only a single file called `jazzer.jar`, which contains the real jar content.

I guess something in the repackaging was broken since `0.19.0`.

[Maven-Central Jar-Link](https://repo1.maven.org/maven2/com/code-intelligence/jazzer/0.20.0/jazzer-0.20.0.jar)
[mvnrepository.com](https://mvnrepository.com/artifact/com.code-intelligence/jazzer/0.20.0)

This leads to errors like: 
`java.lang.ClassNotFoundException: com.code_intelligence.jazzer.Jazzer`

**Comment by fmeum** [comment]
Thanks for the report, I just released 0.20.1.

**Comment by AndreasTu** [comment]
The version `0.20.1` works as expected. 
Thank you for the quick fix.
