### ISSUE TITLE
Hook scope is only system jars(rt.jar)

### ISSUE THREAD

**Issue by fat-ru** [CodeIntelligenceTesting/jazzer#866]
hi!

we found many methods can not be hooked, because hook scope is only system jars(rt.jar).

the question point is as follow:
```
val classfileBuffer = maybeClassfileBuffer ?: ClassGraph()
            .enableSystemJarsAndModules()
            .ignoreClassVisibility()
            .acceptClasses(className)
            .scan()
            .use {
                it.getClassInfo(className)?.resource?.load() ?: run {
                    Log.warn("Failed to load bytecode of class $className")
                    return null
             }
}
```

and we hope other jar can be also hooked, In order to achieve that, the code above should add `acceptLibOrExtJars()` method, the modified code is as follow:
```
val classfileBuffer = maybeClassfileBuffer ?: ClassGraph()
            .enableSystemJarsAndModules()
            .acceptLibOrExtJars()
            .ignoreClassVisibility()
            .acceptClasses(className)
            .scan()
            .use {
                it.getClassInfo(className)?.resource?.load() ?: run {
                    Log.warn("Failed to load bytecode of class $className")
                    return null
             }
}
```

so, can you release a new version base the 0.19.0, for example, the new version is 0.19.1.

thank you very much!

**Comment by fmeum** [comment]
Thanks for the report! 

Do I understand correctly that this would only matter for JDK 8? A standard JDK 17 doesn't seem to have any JARs in the additional places that would be scanned.

Would a regular new release also work for you? Is there a regression in 0.20.0 that prevents you from upgrading?
