### ISSUE TITLE
How to make jazzer get coverage of another process?

### ISSUE THREAD

**Issue by Brokenice0415** [CodeIntelligenceTesting/jazzer#873]
I would like to use jazzer to test a program A, while during program A I start several programs by ProcessBuilder, whose coverage I want jazzer to monitor as well.
Does jazzer support the case I mention?

**Comment by bertschneider** [comment]
Using coverage of external applications is currently not possible in Jazzer.

Is there a reason to not fuzz the other applications directly? This could potentially uncover problems otherwise hidden by the way they are started by the first application.

**Comment by Brokenice0415** [comment]
@bertschneider Thanks for your comment! 

> Is there a reason to not fuzz the other applications directly?

Because in my program, how other external applications run is determined by the first application's actions through inter-process communication. I would like get total coverage instead of that of only the first application or the other applications.
