### ISSUE TITLE
Why can't the cifuzz project be found?

### ISSUE THREAD

**Issue by PoppingSnack** [CodeIntelligenceTesting/jazzer#889]
Why can't the cifuzz project be found?
https://github.com/CodeIntelligenceTesting/cifuzz

**Comment by bertschneider** [comment]
The `cifuzz` repository turned private for now. An official announcement will follow.

**Comment by Djaytan** [comment]
Hello @bertschneider,
Any news on this subject?

**Comment by WSharman1** [comment]
Hi @Djaytan, as mentioned with recent changes of our development focus, we stopped all work on improving Jazzer(.js) in this GitHub repository. Instead we have been working hard to add value to our new CI Fuzz solution, which includes Jazzer and Jazzer.js. If you'd like to know more and I'd be happy to arrange 10-15 minutes for us to talk through your use case.
