### ISSUE TITLE
Broken link in README file

### ISSUE THREAD

**Issue by mernst** [CodeIntelligenceTesting/jazzer#890]
https://github.com/CodeIntelligenceTesting/jazzer#ci-fuzz says:
"The open-source CLI tool cifuzz makes it easy to set up Maven and Gradle projects for fuzzing with Jazzer."

The anchor text "cifuzz" links to https://github.com/CodeIntelligenceTesting/cifuzz, which gives a 404 error.

**Comment by mernst** [comment]
There is also a broken link at https://github.com/CodeIntelligenceTesting (anchor text "CI Fuzz").

**Comment by mernst** [comment]
https://www.code-intelligence.com/cli-tool says to run
```
sh -c "$(curl -fsSL https://raw.githubusercontent.com/CodeIntelligenceTesting/cifuzz/main/install.sh)"
```

When I do so, the result is:
```
% sh -c "$(curl -fsSL https://raw.githubusercontent.com/CodeIntelligenceTesting/cifuzz/main/install.sh)"
curl: (22) The requested URL returned error: 404
```

https://docs.code-intelligence.com/ci-fuzz/how-to/ci-fuzz-installation says:
"Please visit the Download Portal to download the latest releases for Linux, MacOS and Windows."
The link for anchor text "Download Portal" is to https://downloads.code-intelligence.com/ which redirects to https://downloads.code-intelligence.com/login which requires a login.

I think you may not want anyone to use cifuzz.  :smiley:

**Comment by bertschneider** [comment]
Thx for reporting the broken links! Indeed, the cifuzz repository went private, an official announcement is still in the making, though.

#892 removes references to cifuzz in this repository, and the other places should follow shortly.
