### ISSUE TITLE
Failed to test Spring boot project

### ISSUE THREAD

**Issue by MargeD558** [CodeIntelligenceTesting/jazzer#95]
I tried to test a Spring boot project with Jazzer, but it can not get spring context. 

Does Jazzer support testing Spring boot projects? Is there a demo?

**Comment by fmeum** [comment]
While Jazzer by itself is mainly suited for fuzzing libraries, our commercial platform [CI Fuzz](https://www.code-intelligence.com/product-tour), which builds on Jazzer, can fuzz entire web apps and also detect web-specific vulnerabilities.

**Comment by H4de5-7** [comment]
> While Jazzer by itself is mainly suited for fuzzing libraries, our commercial platform [CI Fuzz](https://www.code-intelligence.com/product-tour), which builds on Jazzer, can fuzz entire web apps and also detect web-specific vulnerabilities.

Hi, where can I found CI Fuzz? Is it actively fuzzing or passive fuzzing（when fuzzing web apps)?

**Comment by HenrichN** [comment]
> > While Jazzer by itself is mainly suited for fuzzing libraries, our commercial platform [CI Fuzz](https://www.code-intelligence.com/product-tour), which builds on Jazzer, can fuzz entire web apps and also detect web-specific vulnerabilities.
> 
> Hi, where can I found CI Fuzz? Is it actively fuzzing or passive fuzzing（when fuzzing web apps)?

You can just head over to app.code-intelligence.com and try it out. If you are interested in a demo of fuzzing web apps, don't hesitate to book a demo!

**Comment by H4de5-7** [comment]
> 

Hi, I found the introduction of CI Fuzz mentioned "ci-fuzz-on-prem-installer-<version>-linux", Is this commercial closed source, or can I download it from somewhere?

**Comment by H4de5-7** [comment]
> > > While Jazzer by itself is mainly suited for fuzzing libraries, our commercial platform [CI Fuzz](https://www.code-intelligence.com/product-tour), which builds on Jazzer, can fuzz entire web apps and also detect web-specific vulnerabilities.
> > 
> > 
> > Hi, where can I found CI Fuzz? Is it actively fuzzing or passive fuzzing（when fuzzing web apps)?
> 
> You can just head over to app.code-intelligence.com and try it out. Specifically for web app fuzzing, we recommend that you talk to one of our experts directly and they can get you started quickly: https://www.code-intelligence.com/book-a-demo

Hi, I found the introduction of CI Fuzz mentioned "ci-fuzz-on-prem-installer--linux", Is this commercial closed source, or can I download it from somewhere?

**Comment by HenrichN** [comment]
> Hi, I found the introduction of CI Fuzz mentioned "ci-fuzz-on-prem-installer--linux", Is this commercial closed source, or can I download it from somewhere?

This is our commercial, closed source offering building on top of Jazzer. We are happy to give a demo, if this is interesting for you :-)

**Comment by H4de5-7** [comment]
> > Hi, I found the introduction of CI Fuzz mentioned "ci-fuzz-on-prem-installer--linux", Is this commercial closed source, or can I download it from somewhere?
> 
> This is our commercial, closed source offering built on top of Jazzer. We are happy to give a demo, if this is interesting for you :-)

Got that, thanks for your reply!
